package org.alex73.korpus.editor.ui;

public class GrammarPane3 extends javax.swing.JPanel {

    /**
     * Creates new form GrammarPane3
     */
    public GrammarPane3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelInputParadigm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtLikeParadigm = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtGrammarParadigm = new javax.swing.JTextField();
        panelSaveParadigm = new javax.swing.JPanel();
        cbPreserveCaseParadigm = new javax.swing.JCheckBox();
        btnSaveParadigm = new javax.swing.JButton();
        listScrollParadigm = new javax.swing.JScrollPane();
        tableFoundParadigm = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtOutTagParadigm = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtOutThemeParadigm = new javax.swing.JTextField();
        outScrollParadigm = new javax.swing.JScrollPane();
        outputPanel = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        panelInputParadigm.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Разгортваем");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInputParadigm.add(jLabel1, gridBagConstraints);

        jLabel4.setText("як");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInputParadigm.add(jLabel4, gridBagConstraints);

        txtLikeParadigm.setColumns(10);
        txtLikeParadigm.setToolTipText("Лема слова, на якое мусіць быць падобнае, можна з '*'");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInputParadigm.add(txtLikeParadigm, gridBagConstraints);

        jLabel2.setText("Граматыка");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInputParadigm.add(jLabel2, gridBagConstraints);

        txtGrammarParadigm.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInputParadigm.add(txtGrammarParadigm, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        add(panelInputParadigm, gridBagConstraints);

        panelSaveParadigm.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 0));

        cbPreserveCaseParadigm.setText("Захоўваць вялікія літары");
        panelSaveParadigm.add(cbPreserveCaseParadigm);

        btnSaveParadigm.setText("Захаваць");
        panelSaveParadigm.add(btnSaveParadigm);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        add(panelSaveParadigm, gridBagConstraints);

        listScrollParadigm.setMinimumSize(new java.awt.Dimension(20, 120));
        listScrollParadigm.setPreferredSize(new java.awt.Dimension(2, 120));

        tableFoundParadigm.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listScrollParadigm.setViewportView(tableFoundParadigm);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(listScrollParadigm, gridBagConstraints);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("Тэг:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel4.add(jLabel3, gridBagConstraints);

        txtOutTagParadigm.setColumns(8);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel4.add(txtOutTagParadigm, gridBagConstraints);

        jLabel7.setText("Тэма:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel4.add(jLabel7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel4.add(txtOutThemeParadigm, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jPanel4, gridBagConstraints);

        outScrollParadigm.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        outputPanel.setLayout(new java.awt.GridLayout(1, 0));
        outScrollParadigm.setViewportView(outputPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(outScrollParadigm, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnSaveParadigm;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JCheckBox cbPreserveCaseParadigm;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JScrollPane listScrollParadigm;
    public javax.swing.JScrollPane outScrollParadigm;
    public javax.swing.JPanel outputPanel;
    public javax.swing.JPanel panelInputParadigm;
    public javax.swing.JPanel panelSaveParadigm;
    public javax.swing.JTable tableFoundParadigm;
    public javax.swing.JTextField txtGrammarParadigm;
    public javax.swing.JTextField txtLikeParadigm;
    public javax.swing.JTextField txtOutTagParadigm;
    public javax.swing.JTextField txtOutThemeParadigm;
    // End of variables declaration//GEN-END:variables
}
