package org.alex73.korpus.editor.ui;

public class GrammarPane2 extends javax.swing.JPanel {

    /**
     * Creates new form GrammarPane2
     */
    public GrammarPane2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rbAddParadigm = new javax.swing.JRadioButton();
        rbAddVariant = new javax.swing.JRadioButton();
        rbAddForm = new javax.swing.JRadioButton();
        txtTo = new javax.swing.JTextField();
        scrollTo = new javax.swing.JScrollPane();
        tableTo = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        cbPreserveCase = new javax.swing.JCheckBox();
        btnSave = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtWhat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtLike = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtGrammar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFound = new javax.swing.JTable();
        outScroll = new javax.swing.JScrollPane();
        outPanel = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("Дадаць:");
        jPanel4.add(jLabel3);

        buttonGroup1.add(rbAddParadigm);
        rbAddParadigm.setText("парадыгму");
        jPanel4.add(rbAddParadigm);

        buttonGroup1.add(rbAddVariant);
        rbAddVariant.setSelected(true);
        rbAddVariant.setText("варыянт");
        jPanel4.add(rbAddVariant);

        buttonGroup1.add(rbAddForm);
        rbAddForm.setText("форму");
        jPanel4.add(rbAddForm);

        txtTo.setColumns(10);
        txtTo.setToolTipText("Фільтар па леме ў якую парадыгму дадаваць, з '*'");
        jPanel4.add(txtTo);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(jPanel4, gridBagConstraints);

        scrollTo.setMinimumSize(new java.awt.Dimension(20, 120));
        scrollTo.setPreferredSize(new java.awt.Dimension(20, 120));

        tableTo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollTo.setViewportView(tableTo);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(scrollTo, gridBagConstraints);

        cbPreserveCase.setText("Захоўваць вялікія літары");
        jPanel3.add(cbPreserveCase);

        btnSave.setText("Захаваць");
        jPanel3.add(btnSave);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        add(jPanel3, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Разгортваем");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel1, gridBagConstraints);

        txtWhat.setColumns(10);
        txtWhat.setToolTipText("Слова што разгортваць");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel1.add(txtWhat, gridBagConstraints);

        jLabel4.setText("як");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel4, gridBagConstraints);

        txtLike.setColumns(10);
        txtLike.setToolTipText("Лема слова, на якое мусіць быць падобнае, можна з '*'");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel1.add(txtLike, gridBagConstraints);

        jLabel2.setText("Граматыка");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel2, gridBagConstraints);

        txtGrammar.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel1.add(txtGrammar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        add(jPanel1, gridBagConstraints);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(20, 120));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(2, 120));

        tableFound.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tableFound);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(jScrollPane1, gridBagConstraints);

        outScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        outPanel.setLayout(new java.awt.GridBagLayout());
        outScroll.setViewportView(outPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(outScroll, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnSave;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JCheckBox cbPreserveCase;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPanel outPanel;
    public javax.swing.JScrollPane outScroll;
    public javax.swing.JRadioButton rbAddForm;
    public javax.swing.JRadioButton rbAddParadigm;
    public javax.swing.JRadioButton rbAddVariant;
    public javax.swing.JScrollPane scrollTo;
    public javax.swing.JTable tableFound;
    public javax.swing.JTable tableTo;
    public javax.swing.JTextField txtGrammar;
    public javax.swing.JTextField txtLike;
    public javax.swing.JTextField txtTo;
    public javax.swing.JTextField txtWhat;
    // End of variables declaration//GEN-END:variables
}
